version: '3'
services:
  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3000"
